#

# 输入Gitalk相关设定，即可添加评论区
gitalk:
  clientID: 
  clientSecret: 
  repo: 
  owner: 

# 输入Google Analytics web tracking code
google_analytics:

# 输入你的网站域名（如果你没有添加自己的域名，而是直接用GitHub pages分配的域名的话可以省略）
url: http://mo.b-hu.org 

# 添加你的博客的二级域名，一般来说是你的repository名
# 如果你的博客的URL是：(http://yourusername.github.io/repository-name)
# 那么就写成 "/repository-name"
baseurl: 


#
# !! 以下所有设置都不需要更改 !!
#

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now that you're using
version: v1.2.0

timezone: Asia/Shanghai

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Prose设置
prose:
  rooturl: "_posts"
  siteurl: "http://mo.b-hu.org"
  media: "images"
  metadata:
    _posts:
        - name: "title"
          field:
            element: "text"
            label: "title"


        - name: "data"
          field:
            element: "hidden"
            value: "CURRENT_DATETIME"


        - name: "author"
          field:
            element: "hidden"
            value: "梦貘"


        - name: "categories"
          field:
            element: "text"
            
        - name: "tags"
          field:
            element: "text"
            
        - name: "comments"
          field:
            element: "hidden"
            value: "true"
        
      - name: "layout"
        field:
            element: "hidden"
            value: "blog"
